server:
 port: 9050
 servlet:
  context-path: /poli/v1
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://ec2-44-198-82-71.compute-1.amazonaws.com:5432/d9263lst81bsq8
  username: jogodwreiviatk
  password: d5228f77860ebb4afc41baf7bd8f5441cba1622bbf674f09f519c4ba8bda6a1c
  platform: postgres
 jpa:
  hibernate:
   ddl-auto: create-drop
  generate-ddl: true